### ISSUE TITLE
Gradient tool doesn't seem to allow changing colors

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#140]
Choosing different colors for the gradient tool doesn't update the tool window, and when filling with the gradient it seems to be always gray/white.

**Comment by humdingerb** [comment]
This is fixed by #141, right?
I mean, the updating of the tool setup window. For me, using the fill tool and changing the gradient colours does work anyway.

You have to be aware though, that clicking on the gradient field only opens the clicked colour in the colour palette. Changing the colour in the palette window does not automatically change the gradient. You have to drag'n'drop the new colour onto the gradient.
This isn't obvious, specially as long as #141 isn't merged and you don't see anything in the tool window...

**Comment by dsizzle** [comment]
Hmm, that doesn't sound like a good user experience though.

**Comment by humdingerb** [comment]
Indeed, it'd be nicer if the colour palette reported back to the gradient window and the colours got updated live.

**Comment by dsizzle** [comment]
I think this needs more thought.  I have the 'live update' colors working, but then it continues to update the color as long as the gradient tool is open.  That feels odd too. I am closing this ticket since it works with the drag and drop, so it's not really a bug.  I will open another ticket for upgrading the gradient tools as an enhancement.
