### ISSUE TITLE
build.sh improvement

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#248]
By going back to an older version of the code, I got the "addons/Working" folder back - and this makes builds fail.  It'd be nice if the build either ignored this, or if "clean" would remove that folder perhaps?

It took me a little while to figure out that was the issue. :laughing:

**Comment by humdingerb** [comment]
Wouldn't going back the commits' history also restore the original build.sh ?
Having said that, doing "git reset -hard _oldcommithash_" that should have the Working folder, does not... Weird?
I have empty e.g. `addons/AddOns/AdaptiveHistogramEqualization` folders though. Why?

If you have a quick solution, feel free to modify build.sh, of course. Otherwise, I need some guidance how to actually revert back to the times of the "Working" folder.

**Comment by dsizzle** [comment]
Sorry, I was unclear!

what I meant was that I went back to an old build and everything was fine, but then when I reset back to the most recent build, the old Working folder was still there, and I forgot about it.  If you try to build with that extra Working folder it fails. 

So, my request for enhancement was to have “clean” delete the Working folder if it exists. Not a big deal because I expect the number of times someone will need to go back prior to the folder cleanup is small, but when it does happen it’s confusing.

**Comment by humdingerb** [comment]
Like that: #249 ?
