### ISSUE TITLE
Addon "Stretch histogramm" not working

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#355]
It appears that the addon "Stretch histogramm" (= ContrastManipulator, maybe the source files should be renamed to avoid confusion) doesn't do a thing.

Do I see that right, after all the work, [return original;](https://github.com/HaikuArchives/ArtPaint/blob/master/addons/AddOns/ContrastManipulator/ContrastManipulator.cpp#L149) returns the unmodified bitmap?

**Comment by humdingerb** [comment]
Apparently, I saw this wrong. From the BeBook:

> Bits() [...] Returns a pointer to the bitmap data.

So the work is done on the atual data.
I still don't see any difference, and it appears ArtPaint doesn't either: After invoking the addon, the project isn't marked as changed and needs saving (missing "*" in window title, no entry to "Undo", and no alert to warn when closing).

**Comment by dsizzle** [comment]
It does work but it needs a UI. Basically it tries to stretch the color values to fill the full range. The easiest way to see it is to take a photo and decrease the contrast a lot, and then you’ll see Stretch Histogram try to restore the black and white points. For example if you take an image of a galaxy in space, and mess with the brightness and contrast so that the image is quite gray, then Stretch histogram will make the space black again and the galaxy bright white. 

It would be much easier to understand if you could see the histogram in the UI and also be able to see the effect or control it. 

this addon needs to be renamed and it needs to grow into the equivalent of photoshops “levels” tool.

**Comment by humdingerb** [comment]
Ah, I see. The changes for not totally out of whack images were too subtle for me.

OK, that leaves the "ArtPaint doesn't register a change and won't prompt for saving (missing "*" in window title, no entry to "Undo", and no alert to warn when closing).

**Comment by PeteCA** [comment]
> Ah, I see. The changes for not totally out of whack images were too subtle for me.
> 
> OK, that leaves the "ArtPaint doesn't register a change and won't prompt for saving (missing "*" in window title, no entry to "Undo", and no alert to warn when closing).
> 
Yeah, I notice that on my ancient copy of ArtPaint (I will get into sync at some point,
I hope!) some other add-on operations, like "Wood", also don't trigger a "project
changed" action on exit.  Others, like "Marble" seem to.  (Very brief random testing)

**Comment by dsizzle** [comment]
Well, I think sometimes it *doesnt* change the image. With an “out-of-whack” image the change is registered and there is an Undo entry for Stretch histogram.

**Comment by PeteCA** [comment]
> Well, I think sometimes it *doesnt* change the image. With an “out-of-whack” image the change is registered and there is an Undo entry for Stretch histogram.

I should clarify:  if image is already stretched, the add-on does nothing, and
no "Undo" is generated.  (Which I'd consider correct)  If it's not, an Undo *is*
generated, but "Close" or "Quit" just quits. without any query.

OTOH, "Warp" for example generates both an Undo and a prompt on Quit
if it is used.

**Comment by humdingerb** [comment]
I created #357 that also deals with an undo/save issue that may interfere here.
If that one is solved, we should check which addons still misbehave in that regard.

In any case, the stretch histogram does work, so let'd close the issue.
