### ISSUE TITLE
Edit: Copy/Cut whole layer/canvas when no selection

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#411]
To have everything consistent "none selected" should eqal "all selected" when it comes to Edit | Copy/Cut.

It already does for "Delete" and all transformations (Rotate, Translate, Flip, Crop) and add-ons.

**Comment by dsizzle** [comment]
It actually already works this way.  However, it seems to intermittently not work?  Trying to figure out a pattern...but if you open an image and hit Alt+C, Alt+V it copy/pastes the whole layer.  Trying to do it a second time pastes a blank layer.  But then changing layers and stuff it works again.  Until it doesn't.  So, the behavior is already consistent - there's just some bug that seems to be making it flaky?

**Comment by dsizzle** [comment]
It actually already works this way.  Does it not work for you?  It works fine on my end.

**Comment by humdingerb** [comment]
Weird. Could swear it didn't before. After a sync with master and clean build it does indeed work.
Sorry about the noise.

**Comment by dsizzle** [comment]
No worries! 

I did notice something odd, and maybe this is what you ran into: because of #403 I sometimes needed to click on the canvas window to focus it. If I had the Selection tool active, and I clicked on the image itself to get focus, it must’ve been creating an infinitely tiny “selection” that was invisible because the cut/copy was blank. 

If I had any other tool active, or click on the window tab, it works fine. So either #403 needs to be fixed, or maybe the 1-pixel selection issue?

**Comment by humdingerb** [comment]
> So either https://github.com/HaikuArchives/ArtPaint/issues/403 needs to be fixed, or maybe the 1-pixel selection issue?

Implementing #403 would be nice either way. :)
If you mean #410 with the "1-pixel selection issue", I've commented there.
