### ISSUE TITLE
Lots of Add-Ons still broken/not working

### ISSUE THREAD

**Issue by CodeforEvolution** [HaikuArchives/ArtPaint#48]
This is left over from when I added Makefiles to add-ons and allowed them to build with ArtPaint, #47 . I found many add-ons upon running or doing a certain function crash ArtPaint and some not do what they say they're supposed to do. The add-ons that need investigating are within the folder addons/AddOns/Not-Working and Crashes-ArtPaint. 

# They are:

### Crashes-ArtPaint:

- [ ] ColorReducer
- [ ] GaussianBlur
- [ ] Sharpness

### Not-Working (As Addon Name Infers...):

- [ ] Brightness
- [ ] Contrast
- [ ] ContrastManipulatorAddon
- [ ] Interference
- [ ] Saturation
- [ ] Threshold

**Comment by PeteCA** [comment]
Is this still the case for you? The menu would be empty if the add-ons folder is not in the artpaint folder (or of course if no canvas has been created)..  The current HaikuPorts release seems to include the add-ons.

**Comment by CodeforEvolution** [comment]
The addons are built, but not all of them. If you look in the addons folder it is sorted into not working, broken, and working. Currently, only the addons in the working folder are built. The others don't work as said or don't work at all.

**Comment by PeteCA** [comment]
The "not working" set unfortunately includes a couple of rather vital ones... "Brightness" and "Contrast" in particular.  I'm hoping I might get around to taking a look soon.

**Comment by digib0y** [comment]
@PeteCA What should be my first approch to fix the add-ons?

**Comment by PeteCA** [comment]
On Thu, Mar 30, 2017 at 01:49:01AM -0700, Deepanshu Goyal wrote:
> @PeteCA What should be my first approch to fix the add-ons?

Sorry -- they're already fixed! (:-))  Turned out to be a simple error (4 years ago) that was the same one I fixed for dynamic display.  So it was just a matter of going through the sources and inserting the same fix.  I'll put in a PR later today.  (This applies to all the "Not Working" ones.  I haven't really checked the "Crtashing" ones, but so far I no longer see a crash.)

**Comment by PeteCA** [comment]
Deepanshu -- if you want something to work on, one annoyance for me is that the PaintWindow gets  stuck at a large size when you drag it larger. (Yes -- I should add an issue, but while I'm here....)  This is something to do with the Layout scheme (didn't happen before that was added).  Haven't delved into it myself, so if you want to have a go...

**Comment by digib0y** [comment]
@PeteCA This doesn't exists for me. I just tried to replicate and works like charm for me.

**Comment by PeteCA** [comment]
You're referring to the window size?  If you're using a current build of ArtPaint, try creating a small (default) canvas, drag the window to nearly full screen, then try to drag it back small.  For me, it "sticks" at the large size or close to it.  (Possible something's changed in the Layout handler since my Haiku rev, but I doubt it.)

**Comment by humdingerb** [comment]
Indeed, there's only the "Working" folder left in the "AddOns". I suppose those could be moved out of that folder...
