### ISSUE TITLE
Using Scale to just move doesn't register in undo buffer

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#493]
You can use Scale to keep the size at 100%, but move the pixels. That apparently doesn't produce an entry in the undo buffer. Should it say "Undo Scale" or can it recognize the "scale" was actually just a "translate"?

**Comment by dsizzle** [comment]
Ah. Yeah. I think if no size change is detected, it doesn't register, to prevent from adding an Undo if the user just clicks ok without changing anything.  it should detect translates as changes too.  Good find!

Anyway, it'll have to say "Undo Scale" because it's a different manipulator. Making it into a Translate might not behave well.

**Comment by humdingerb** [comment]
Having it added to the undo buffer is the important thing, the menu label is a detail... :)
