### ISSUE TITLE
Regression: Airbrush lags

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#642]
Drawing with Airbrush (not "Spray") is very laggy. No other tool seems to be effected.
This is the regressing change: 31949a94cd0a5dffe638b9f4101d06dde72f068a

**Comment by dsizzle** [comment]
Can you describe the "lag"?  I don't see a difference in the Airbrush before and after that change.  The *size* of the Airbrush definitely seems to affect the perceived "lag" - smaller sizes of brush don't connect to each other. I think this might be because a lot of the other tools (all?) use a combination of dots + lines to give the illusion of a smooth curve, but the Airbrush only sprays a "dot" with no connecting line between so the smaller the brush size, the farther apart the dots are. 

I tried to draw some smooth, medium-speed strokes, a few with size 86 and one with size 17 (both with flow of 100). 
before 31949a9: 
![0air](https://github.com/HaikuArchives/ArtPaint/assets/10878750/06ff08d8-ed98-4021-8056-a59ee4949f3a)

after: 
![01air](https://github.com/HaikuArchives/ArtPaint/assets/10878750/d591b6c9-a602-4168-a317-cf9cef915263)

IMHO the feeling is pretty similar?

**Comment by humdingerb** [comment]
To illustrate, here's a video uing airbrush with size 50 and flow 50: https://0x0.st/HtAn.mp4
See how the paint follows the pointer at a distance, catching up with it after Mousy waiting patiently for about a second.

**Comment by dsizzle** [comment]
huh???  The airbrush doesn't behave like that on my machine *at all* - it does that if I change the "NO_INTERPOLATION" in the AirBrushTool.cpp to "LINEAR_INTERPOLATION" but that's not what the current code shows... ? ? ?

I don't get a smooth laggy line, I get a spotty line if I move quickly, or a smooth line if I move slowly.

**Comment by dsizzle** [comment]
Closed via #645
