### ISSUE TITLE
x86_64 seems to be broken

### ISSUE THREAD

**Issue by stippi** [HaikuArchives/ArtPaint#81]
I've tried the 64bit version, and the image/canvas is just black, I cannot pick any colors in the lower right corner... I can't really do anything.

**Comment by PeteCA** [comment]
32-bit ArtPaint is pretty unusable now as well, as I note in the previous issue.
Any attempt to make a selection just results in a black region (rather than an outline), which makes most usage of the feature cumbersome or impossible.  I have to go back to my several-year-old partirion to have it work properly.  (ArtPaint itself hasn't changed in the meantime.)

**Comment by dsizzle** [comment]
In Image::DoRender, there's an #if __POWERPC__ ... clause - and it seems to be the default?  If you compile with -D__INTEL__, the blackness is gone and you can use the tool.

now, there are still plenty of other issues, like color doesn't seem to work at all, but at least you can see the canvas etc.

**Comment by korli** [comment]
When POWERPC actually means big endian, it would be better to use the correct macros:

#include <endian.h>

#if BYTE_ORDER == BIG_ENDIAN

**Comment by dsizzle** [comment]
B_HOST_IS_BENDIAN was also suggested.

**Comment by korli** [comment]
> B_HOST_IS_BENDIAN was also suggested.

BeOS style, yes, it's not in endian.h, but in ByteOrder.h (which actually includes endian.h).
